package org.jack;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.AdjustmentEvent;
import java.awt.event.AdjustmentListener;

public class DownloaderGUI extends JFrame {
    private JPanel DownloaderPanel;
    private JTextPane console;
    private JScrollPane scrollPane1;
    private final Options options;

    public DownloaderGUI(Options options) {
        this.options = options;
        $$$setupUI$$$();
        scrollPane1.getVerticalScrollBar().addAdjustmentListener(e -> e.getAdjustable().setValue(e.getAdjustable().getMaximum()));
    }

    public void createWindow() {
        try {
            setLocationByPlatform(true);
            setContentPane(DownloaderPanel);
            setTitle("Downloader");
            setSize(400, 225);
            setLocationRelativeTo(null);
        } catch (IllegalComponentStateException ignored) {
        } // ignores error if window is already visible
        setVisible(true);
    }

    public void addLine(String text) {
        console.setText(console.getText() + text + "\n");
    }

    public JTextPane getConsole() {
        return console;
    }

    public Options getOptions() {
        return options;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        DownloaderPanel = new JPanel();
        DownloaderPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        DownloaderPanel.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        console = new JTextPane();
        console.setEditable(false);
        scrollPane1.setViewportView(console);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return DownloaderPanel;
    }

    private void createUIComponents() {
        scrollPane1 = new JScrollPane();
    }
}
